### ISSUE TITLE
Exception while fetching data from Firestore:"Expected a value of type 'JSObject<tl>', but got one of type 'NativeJavaScriptObject'"

### ISSUE THREAD

**Issue by renannery** [FirebaseExtended/firebase-dart#288]
I'm getting this error when I try to get the data from a specific collection in my Firestore database:

> Expected a value of type 'JSObject<tl>', but got one of type 'NativeJavaScriptObject'

For some reason, it only happens with one collection. I wonder if this is something related to a not support type of field.

I assume the issue is inside the method `dartify`

_Environment_
**flutter** 1.12 
**firebase** ^7.1.0

Let me know if I can provide something else in order to have this fixed.

**Comment by kevmoo** [comment]
Could you go to the firebase console and take a screenshot of an example node that fails here?

Make SURE there is no sensitive data in the screenshot.

**Comment by raphael-bmec-co** [comment]
I am having this issue when trying to upload data with the code below.

I see someone else posted the same issue but it was closed: https://github.com/FirebaseExtended/firebase-dart/issues/263

`
try {
      return _firebase
          .storage()
          .ref()
          .child(fileName)
          .put(bytes)
          .future
          .then((_) {
        log.i("upload complete");
      }).catchError((error) {
        log.wtf("Sign in error: ${error.message}");

        _scaffoldKey.currentState.showSnackBar(ErrorSnackBar(
          contentText: "Sign in error: ${error.message}",
        ));
//      throw (error);
      });
    } catch ( e){

//    NativeJavaScriptObject a;

      log.e(e.runtimeType);
      log.e(e);
    }
`

**Comment by raphael-bmec-co** [comment]
Okay I have some good news. 

What we are seeing: This seems to be an issue with the native error handler parsing the thrown object into an error. This appears to be because the object is of type NativeJavaScriptObject.

Good news: You can still expand the NativeJavaScriptObject to see the actual error being thrown by the Firebase API by referencing error.code, error.message etc etc.

Happy coding.

**Comment by cfregin** [comment]
I got that error when using a map with the properties: latitude,longitude. dartify try's
to convert them into a GeoPoint which fails when it is not saved as geopoint already.

**Comment by MatanLjubas** [comment]
I'm also experiencing the same issue as @cfregin.

**Comment by Vichet97** [comment]
It's type error exception, can be fixed by try-catch in `dartify` function at `/lib/src/utils.dart`

``` 
if (util.hasProperty(jsObject, 'latitude') &&
      util.hasProperty(jsObject, 'longitude') &&
      js.objectKeys(jsObject).length == 2) {
    // This is likely a GeoPoint – return it as-is
    // return jsObject as GeoPoint;
    try{
      return jsObject as GeoPoint;
    } catch(e) {
      //Handle type error exception
    }
  }
```

**Comment by bankenro** [comment]
Someone managed to fix it? I have been paralyzed for this error for 2 days

**Comment by BaR488** [comment]
Hi!

I'm experiencing the same issue.
In my case field with location type save to firestore as Map. 
I fix my serialization, and save as [GeoPoint](https://pub.dev/documentation/firebase/latest/firebase_firestore/GeoPoint-class.html).
Check your firebase console.

**Comment by kevmoo** [comment]
This is a gnarly one. There is no good way to detect if one is using the actual GeoPoint object or something synthetic...hrm...

**Comment by devj3ns** [comment]
I'm experiencing the same issue on my web build. The half of the time I am getting this error:

```Expected` a value of type 'JSObject<Yi>', but got one of type 'NativeJavaScriptObject'```

I tried different firebase js versions, but it does not work.

**Comment by karabanovbs** [comment]
@devj3ns are you use geopoint?
[comment](https://github.com/FirebaseExtended/firebase-dart/issues/288#issuecomment-705250000)

**Comment by devj3ns** [comment]
@karabanovbs 
No, I am not using that.

**Comment by EightRice** [comment]
why is this closed? where's the solution? This has been blocking me for 3 days now.. can't parse any data coming in from ethereum.. I've been working on this for two months just to hit this dead end. Please, does anybody know what to do with that NativeJavaScriptObject that prints out like [object Object] ?

**Comment by kevmoo** [comment]
@EightRice – I believe it was fixed.

To debug, try printing the object with https://api.dart.dev/stable/2.12.2/dart-html/Console/debug.html

**Comment by EightRice** [comment]
> @EightRice – I believe it was fixed.
> 
> To debug, try printing the object with https://api.dart.dev/stable/2.12.2/dart-html/Console/debug.html

So I'm not getting the debug method.. is there something I need to import please? I tried importing dart:html, but it still doesn't let me use the debug function. I appreciate the help.

**Comment by kevmoo** [comment]
https://api.dart.dev/stable/2.12.2/dart-html/window.html

`window.console.debug` should work

**Comment by EightRice** [comment]
it is simply printing out [object Object], same as if you just print(item)

**Comment by EightRice** [comment]
> https://api.dart.dev/stable/2.12.2/dart-html/window.html
> 
> `window.console.debug` should work

it is simply printing out [object Object], same as if you just print(item). I know there's supposed to be a sting in there somewhere, but not sure how to get to it.

**Comment by kevmoo** [comment]
@EightRice – send me a message on twitter – let's VC quick and I'll help you!

**Comment by EightRice** [comment]
> @EightRice – send me a message on twitter – let's VC quick and I'll help you!

this is really cool of you. I sent you a DM on Twitter with a link to a zoom room.

**Comment by RQ2L84Q-ROW** [comment]
Hi I faced a similar issue recently. Does anyone has a solution for this?
